# workflow for testing multipoint cap reading script

name: MicroPython Code Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # check if job can be called test
  test:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup python
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # # Install dependancies
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r ./requirements.txt

      # Run tests
      - name: Run tests with unittest
        run: |
          cd mp-tests
          python -m unittest test_cap_reading.py
